[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-ye111566-land"
version = "2.0.0"
description = "领地"

[project.entry-points."endstone"]
claim_chunk = "endstone_land:ClaimChunk"
